stages:
  - replace_ports
  - build
variables:
  DOCKER_HOST: "/var/run/docker.sock"

replace:
  stage: replace_ports
  script:
    - sed -i 's/80:80/32080/' docker-compose.yml
    - sed -i 's/443:443/32443/' docker-compose.yml


build-job:
  stage: build

  script:
    - git submodule init
    - git submodule update
    - docker-compose build