stages:
  - replace_ports
  - submodules
  - build
  - deploy
  - notification


replace:
  stage: replace_ports
  script:
    - sed -i 's/80:80/32080/' docker-compose.yml
    - sed -i 's/443:443/32443/' docker-compose.yml
    - sed -i 's/5432:5432/5433:5432' docker-compose.yml

update-submodules:
  stage: submodules
  script:
    - git submodule init
    - git submodule update

build:
  stage: build

  script:
    - docker-compose build
deploy:
  stage: deploy
  script:
    - docker-compose up -d

alert-success:
  stage: notification
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
  when: on_success 
alert-failed:
  stage: notification
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
  when: on_failure 