version: "3.7"

services:
  app:
    container_name: lazer-server
    build: 
      dockerfile: OsuLazerServer/Dockerfile
      context: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=lazer
      - DB_PASS=123321
      - REDIS_URL=cache:6379
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    volumes:
      - "./replays:/app/replays:rw"
    networks:
      - lazer
  db:
    container_name: lazer-server-db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES=USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=lazer
    ports:
      - 5432:5432
    networks:
      - lazer
  cache:
    container_name: lazer-server-cache
    restart: always
    image: redis:7.0-rc2
    networks:
      - lazer
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  

networks:
  lazer:
    driver: bridge
volumes: 
    pgdata: {}
#
